pageInfo:
  title: Maniak Academy Lab
sections: # An array of sections
- name: Example
  icon: far fa-rocket
  items:
  - title: GitHub
    description: Maniak Academy GitHub
    icon: fab fa-github
    url: https://github.com/maniak-academy
- name: Local Services
  items:
  - title: Firewall
    icon: favicon
    url: http://172.16.10.1/
  - title: Game Server
    icon: https://i.ibb.co/710B3Yc/space-invader-x256.png
    url: http://172.16.10.1/